apiVersion: v1
kind: Service
metadata:
  name: {{ include "task2.fullname" . }}-external
  labels:
    {{- include "task2.labels" . | nindent 4 }}
spec:
  type: NodePort
  ports:
    - port: {{ .Values.service.httpPort }}
      targetPort: {{ .Values.service.httpPort }}
      nodePort: 30123  # Порт в диапазоне 30000-32767
      name: http
    - port: {{ .Values.service.nativePort }}
      targetPort: {{ .Values.service.nativePort }}
      nodePort: 30124  # Порт в диапазоне 30000-32767
      name: native
  selector:

    {{- include "task2.selectorLabels" . | nindent 4 }}
