apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "task2.fullname" . }}-data
  labels:
    {{- include "task2.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.resources.requests.storage }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "task2.fullname" . }}-logs
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.resources.requests.storage }}