apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "task2.fullname" . }}-deployment
  labels:
    {{- include "task2.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: {{ .Values.strategy.type }}
  selector:
    matchLabels:
      {{- include "task2.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "task2.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      containers:
        - name: {{ .Chart.Name }}-container
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.httpPort }}
            - name: native
              containerPort: {{ .Values.service.nativePort }}
          {{- with .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      volumes:
        - name: config
          configMap:
            name: {{ include "task2.fullname" . }}-config
        - name: users
          configMap:
            name: {{ include "task2.fullname" . }}-users
        - name: data
          persistentVolumeClaim:
            claimName: {{ include "task2.fullname" . }}-data
        - name: logs
          persistentVolumeClaim:
            claimName: {{ include "task2.fullname" . }}-logs

      